---
    wssd_DTS_dir: DTS_files/500_bp_slide
    sunk_DTS_dir: DTS_files/500_bp_sunk_slide
    gglob_dir: gglob
    wnd_slide: 100
    wnd_size: 500
    reference: hg19
    hg19: 
        wssd_wnd_contigs: /net/eichler/vol7/home/psudmant/EEE_Lab/1000G/1000genomesScripts/windowed_analysis/DTS_window_analysis/windows/hg19_slide/500_bp_windows.pkl.contigs
        sunk_wnd_contigs: /net/eichler/vol7/home/psudmant/EEE_Lab/1000G/1000genomesScripts/windowed_analysis/DTS_window_analysis/windows/hg19_sunk_slide/500_bp_windows.sunks.pkl.contigs
    
    hg38: 
        wssd_wnd_contigs: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/DTS_windows/hg38_slide/500_bp_windows.pkl
        sunk_wnd_contigs: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/DTS_windows/hg38_sunk_slide/500_bp_windows.sunks.pkl
